# Generated by Django 6.0.3 on 2026-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('requiere_formula', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('via_administracion', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('concentracion', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicamentos/')),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
    ]
