# Generated by Django 6.0.3 on 2026-04-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentracion',
            fields=[
                ('id_concentracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_concentracion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'concentracion',
            },
        ),
        migrations.CreateModel(
            name='EstadoMedicamento',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_medicamento',
            },
        ),
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id_forma_farmaceutica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma_farmaceutica', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forma_farmaceutica',
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proveedores_aux',
            },
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('id_via_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_via_administracion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'via_administracion',
            },
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='forma_farmaceutica',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='medicamentos',
            name='via_administracion',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='concentracion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='nombre_medicamento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='requiere_formula',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='stock',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.estadomedicamento'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_forma_farmaceutica',
            field=models.ForeignKey(blank=True, db_column='id_forma_farmaceutica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.formafarmaceutica'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.laboratorios'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.proveedores'),
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_via_administracion',
            field=models.ForeignKey(blank=True, db_column='id_via_administracion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.viaadministracion'),
        ),
    ]
