# Generated by Django 5.2.6 on 2026-04-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.CharField(max_length=50)),
                ('farmaceuta', models.CharField(max_length=50)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
