# Generated by Django 5.2.6 on 2026-04-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField(unique=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50)),
                ('farmaceuta', models.CharField(max_length=50)),
                ('descuento_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_venta', models.CharField(choices=[('Activo', 'ACTIVO'), ('Cancelado', 'CANCELADO'), ('Confirmado', 'CONFIRMADO')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ventas')),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
    ]
