# Generated by Django 5.2.6 on 2026-04-08 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventas',
            table=None,
        ),
    ]
