# Generated by Django 5.2.6 on 2026-04-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.IntegerField(unique=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=50)),
                ('farmaceuta', models.CharField(max_length=50)),
                ('descuento_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_venta', models.CharField(choices=[('Activo', 'ACTIVO'), ('Cancelado', 'CANCELADO'), ('Confirmado', 'CONFIRMADO')], default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.ventas')),
            ],
        ),
    ]
