# Generated by Django 5.2.6 on 2026-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=True)),
                ('nombre_contacto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
