# Generated by Django 6.0.3 on 2026-04-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_detalleventa_producto_alter_detalleventa_venta'),
        ('suppliers', '0002_alter_ventas_table'),
    ]

    operations = [
    ]
