# Generated by Django 6.0.3 on 2026-04-07 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concentracion',
            fields=[
                ('id_concentracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_concentracion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'concentracion',
            },
        ),
        migrations.CreateModel(
            name='EstadoMedicamento',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_medicamento',
            },
        ),
        migrations.CreateModel(
            name='FormaFarmaceutica',
            fields=[
                ('id_forma_farmaceutica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_forma_farmaceutica', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'forma_farmaceutica',
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_laboratorio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proveedores_aux',
            },
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('id_via_administracion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_via_administracion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'via_administracion',
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('stock', models.CharField(max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requiere_formula', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
                ('descripcion', models.CharField(max_length=255)),
                ('concentracion', models.CharField(blank=True, default='', max_length=50)),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.estadomedicamento')),
                ('id_forma_farmaceutica', models.ForeignKey(blank=True, db_column='id_forma_farmaceutica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.formafarmaceutica')),
                ('id_laboratorio', models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.laboratorios')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.proveedores')),
                ('id_via_administracion', models.ForeignKey(blank=True, db_column='id_via_administracion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.viaadministracion')),
            ],
            options={
                'db_table': 'medicamentos',
            },
        ),
    ]
