# Generated by Django 6.0.3 on 2026-04-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='medicamentos/'),
        ),
        migrations.AlterModelTable(
            name='proveedores',
            table='proveedores',
        ),
    ]
