# Generated by Django 6.0.3 on 2026-04-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_medicamentos_imagen_alter_proveedores_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubformaFarmaceutica',
            fields=[
                ('id_subforma_farmaceutica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_subforma_farmaceutica', models.CharField(max_length=100)),
                ('id_forma_farmaceutica', models.ForeignKey(blank=True, db_column='id_forma_farmaceutica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.formafarmaceutica')),
            ],
            options={
                'db_table': 'subforma_farmaceutica',
            },
        ),
        migrations.AddField(
            model_name='medicamentos',
            name='id_subforma_farmaceutica',
            field=models.ForeignKey(blank=True, db_column='id_subforma_farmaceutica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.subformafarmaceutica'),
        ),
    ]