# Generated by Django 6.0.3 on 2026-04-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_proveedores_id_proveedor_proveedores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='proveedores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
